amcl:
  ros__parameters:
    use_sim_time: false
bt_navigator:
  ros__parameters:
    use_sim_time: false
    odom_topic: /ugv/odometry/filtered
bt_navigator_navigate_through_poses_rclcpp_node:
  ros__parameters:
    use_sim_time: false
bt_navigator_navigate_to_pose_rclcpp_node:
  ros__parameters:
    use_sim_time: false
controller_server:
  ros__parameters:
    use_sim_time: false
    odom_topic: /ugv/odometry/filtered
local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: false
global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: false
map_server:
  ros__parameters:
    use_sim_time: false
map_saver:
  ros__parameters:
    use_sim_time: false
planner_server:
  ros__parameters:
    use_sim_time: false
smoother_server:
  ros__parameters:
    use_sim_time: false
behavior_server:
  ros__parameters:
    use_sim_time: false
robot_state_publisher:
  ros__parameters:
    use_sim_time: false
waypoint_follower:
  ros__parameters:
    use_sim_time: false
velocity_smoother:
  ros__parameters:
    use_sim_time: false
    odom_topic: /ugv/odometry/filtered
