twist_mux:
  ros__parameters:

    topics:
      navigation:
        topic: /ugv/cmd_vel_nav
        timeout: 0.5
        priority: 80

      estop:
        topic: /ugv/cmd_vel_estop
        timeout: 0.1
        priority: 100

      teleop_normal:
        topic: /ugv/cmd_vel_normal
        timeout: 0.15
        priority: 60

      teleop_keyboard:
        topic: /ugv/cmd_vel_keyboard
        timeout: 0.08
        priority: 55

      teleop_slow:
        topic: /ugv/cmd_vel_slow
        timeout: 0.15
        priority: 50

    locks:
      safety_watchdog:
        topic: /ugv/watchdog/lock
        timeout: 0.0          
        priority: 255
